name: Publish Package

on:
  workflow_dispatch:

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'freewheel/code-kitchen'
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Set node version to 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Build code-kitchen
        run: |
          cd packages/code-kitchen
          pnpm run build
      - name: Release
        run: pnpm semantic-release -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
